
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0.1

workflows:
  main:
    jobs:
      - orb-tools/publish:
          filters:
            branches:
              only: master
          orb-path: orb.yml
          orb-ref: mattwelke/circleci-orb-test@0.0.2