
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8

workflows:
  main:
    jobs:
      - orb-tools/publish-dev:
          orb-name: mattwelke/circleci-orb-test
          orb-path: orb.yml
          validate: true
          checkout: true
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              only: master
          orb-name: mattwelke/circleci-orb-test
          publish-version-tag: false
          requires:
            - orb-tools/publish-dev